jifa:
  role: standalone-worker
  storage-path: ${user.home}/jifa-storage

spring:
  servlet:
    multipart:
      max-request-size: 512MB
      max-file-size: 512MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  task.scheduling.pool.size: 8

server:
  tomcat:
    relaxed-query-chars:
      - '['
      - ']'

