name: docker

on: workflow_dispatch

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - id: read-version
        run: |
          version=$(head -n 1 version)
          echo "::set-output name=version::$version"
      - name: Use Version
        run: | 
          echo ${{ steps.read-version.outputs.version }}
#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v3
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#      - name: Login to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.JIFA_DOCKER_USERNAME}}
#          password: ${{ secrets.JIFA_DOCKER_PASSWORD}}
#      - name: Build and push
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          platforms: linux/amd64,linux/arm64
#          push: true
#          tags: jifadocker/jifa:latest