#
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#

name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.JIFA_DOCKER_USERNAME}}
          password: ${{ secrets.JIFA_DOCKER_PASSWORD}}
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build.Dockerfile
          tags: jifa-build:latest
          platforms: linux/amd64
          load: true
          build-args: |
            ECLIPSE_MAT_DEPS_OS=linux
            ECLIPSE_MAT_DEPS_ARCH=amd64
          push: false
      - run: |
          rm -rf ./jifa-build
          rm -rf ./jifa-artifacts
          mkdir jifa-build
          mkdir jifa-artifacts
          docker create --name jifa-build jifa-build:latest
          docker cp jifa-build:/workspace/server/build/dependency jifa-build/amd64
          docker cp jifa-build:/workspace/server/build/distributions/jifa.zip jifa-artifacts/jifa-linux-amd64.zip
          docker rm jifa-build
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build.Dockerfile
          tags: jifa-build:latest
          platforms: linux/amd64
          load: true
          build-args: |
            ECLIPSE_MAT_DEPS_OS=linux
            ECLIPSE_MAT_DEPS_ARCH=aarch64
          push: false
      - run: |
          docker create --name jifa-build jifa-build:latest
          docker cp jifa-build:/workspace/server/build/dependency jifa-build/arm64
          docker cp jifa-build:/workspace/server/build/distributions/jifa.zip jifa-artifacts/jifa-linux-arm64.zip
          docker rm jifa-build
      - name: Final Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./final.Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: jifadocker/jifa:latest,jifadocker/jifa:${{ github.ref }}
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .jifa-artifacts/jifa-linux-amd64.zip
          asset_name: jifa-linux-amd64.zip
          asset_content_type: application/zip
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: .jifa-artifacts/jifa-linux-arm64.zip
          asset_name: jifa-linux-arm64.zip
          asset_content_type: application/zip
