#
# Copyright (c) 2023 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0
#
# SPDX-License-Identifier: EPL-2.0
#

name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to release'
        required: true

env:
  REGISTRY_IMAGE: eclipsejifa/jifa

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        platform:
          - linux/amd64
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.tag }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY_IMAGE }}
      - id: read-version
        run: |
          version=$(head -n 1 version)
          echo "::set-output name=version::$version"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./build.Dockerfile
          platforms: ${{ matrix.platform }}
          push: false
          load: true
          tags: jifa-local-build:latest
      - name: Final Build
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./final.Dockerfile
          platforms: ${{ matrix.platform }}
          push: false